<a href="https://colab.research.google.com/github/Precyors/NLP/blob/main/Text_summarization_week4_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install transformers torch


In [ ]:
# Create summary pipeline

from transformers import pipeline

summarizer = pipeline(
    "summarization",
    model="facebook/bart-large-cnn"
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Device set to use cpu


In [ ]:
text = """
The Birth of the Milky Way,[1] also sometimes known as The Origin of the Milky Way,[2] is an oil-on-canvas painting by the Flemish artist Peter Paul Rubens, produced between 1636 and 1638 and featuring the Greco-Roman myth of the origin of the Milky Way. The painting depicts Hera (Juno), spilling her breast milk, the infant Heracles (Hercules) and Zeus (Jupiter) in the background, identifiable by his eagle and lightning bolts. Hera's face is modelled on Rubens' wife, Hélène Fourment.[1] The carriage is pulled by peacocks,[3] a bird which the ancient Greeks and Romans considered sacred to both themselves and to Hera/Juno, as a result of their ability to signal changes in weather through cries and hence their perceived connection to the gods.[4]

With a width of 244 cm (96 in) and height of 181 cm (71 in),[1] the image was a part of the commission from Philip IV of Spain for Rubens, along with other painters such as Diego Velázquez, to decorate Torre de la Parada,[5] the monarch's recreational house and hunting lodge located on Monte de El Pardo. The commission consisted of 112 paintings based on Ovid's Metamorphoses, including this painting.[6] The latter is now held in room 79 at the Museo del Prado, in Madrid,[1] with inventory number P01668 """


In [ ]:
# Get Summary
summary = summarizer(
    text,
    max_length=200,
    min_length=25,
    do_sample=False
)

print("Summary:")
print(summary[0]["summary_text"])


Summary:
The Birth of the Milky Way is an oil-on-canvas painting by the Flemish artist Peter Paul Rubens, produced between 1636 and 1638. The painting depicts Hera (Juno), spilling her breast milk, the infant Heracles (Hercules) and Zeus (Jupiter) in the background. Hera's face is modelled on Rubens' wife, Hélène Fourment. The carriage is pulled by peacocks, a bird which the ancient Greeks and Romans considered sacred.


## Selected NLP Task

The selected NLP task is **text summarization**, which involves reducing long documents into shorter versions while retaining the main ideas. This assignment focuses on abstractive summarization, where the model generates new sentences rather than simply extracting phrases from the original text.

# Steps of Implementation

The Hugging Face Transformers library was used to implement the summarization task. A pretrained BART model (facebook/bart-large-cnn) was loaded using the summarization pipeline. The sample text provided detailed information about **“The Birth of the Milky Way”**, an oil painting by Peter Paul Rubens.

The model processed the input text and generated a concise summary highlighting the most important aspects, including the artist, the subject matter, and key symbolic elements. Parameters such as min_length and max_length were specified to control the output size and maintain readability

# Observed Results

The model successfully produced the following summary:

“The Birth of the Milky Way is an oil-on-canvas painting by the Flemish artist Peter Paul Rubens, produced between 1636 and 1638. The painting depicts Hera (Juno), spilling her breast milk, the infant Heracles (Hercules) and Zeus (Jupiter) in the background. Hera's face is modelled on Rubens' wife, Hélène Fourment. The carriage is pulled by peacocks, a bird which the ancient Greeks and Romans considered sacred.

**Observations:**

-The summary captured the core information of the original text, including the artist, time period, characters, and symbolic elements.

-It condensed a long and complex paragraph into a short, readable version without losing important details.

-Minor contextual or background details (e.g., the commission from Philip IV or museum location) were omitted, which is expected in abstractive summarization, as the model focuses on key points.

-The summary remains coherent and human-readable, demonstrating the effectiveness of the BART model for summarizing descriptive text.